create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in ('admin','mahasiswa')) default 'mahasiswa',student_id uuid unique references public.students(id) on delete cascade,created_at timestamptz not null default now());
alter table public.profiles enable row level security;
create or replace function public.current_user_role() returns text language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() $$;
alter table public.attendance add column if not exists latitude double precision;alter table public.attendance add column if not exists longitude double precision;alter table public.attendance add column if not exists accuracy_meters double precision;alter table public.attendance add column if not exists distance_meters double precision;alter table public.attendance add column if not exists location_valid boolean default false;
drop policy if exists "authenticated can insert attendance" on public.attendance;drop policy if exists "authenticated can update attendance" on public.attendance;drop policy if exists "authenticated can delete attendance" on public.attendance;drop policy if exists "authenticated can read attendance" on public.attendance;
create policy "read own or admin attendance" on public.attendance for select to authenticated using(public.current_user_role()='admin' or student_id=(select student_id from public.profiles where id=auth.uid()));create policy "admin update attendance" on public.attendance for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');create policy "admin delete attendance" on public.attendance for delete to authenticated using(public.current_user_role()='admin');
drop policy if exists "authenticated can read students" on public.students;drop policy if exists "authenticated can insert students" on public.students;drop policy if exists "authenticated can update students" on public.students;drop policy if exists "authenticated can delete students" on public.students;
create policy "read own or admin students" on public.students for select to authenticated using(public.current_user_role()='admin' or id=(select student_id from public.profiles where id=auth.uid()));create policy "admin insert students" on public.students for insert to authenticated with check(public.current_user_role()='admin');create policy "admin update students" on public.students for update to authenticated using(public.current_user_role()='admin') with check(public.current_user_role()='admin');create policy "admin delete students" on public.students for delete to authenticated using(public.current_user_role()='admin');
create or replace function public.submit_attendance(p_student_id uuid,p_lat double precision,p_lng double precision,p_accuracy double precision) returns json language plpgsql security definer set search_path=public as $$ declare v_role text;v_sid uuid;v_distance double precision;v_id uuid;begin select role,student_id into v_role,v_sid from public.profiles where id=auth.uid();if v_role is null then raise exception 'Profil akun belum dibuat.';end if;if v_role='mahasiswa' and v_sid<>p_student_id then raise exception 'Anda hanya boleh absen untuk akun sendiri.';end if;if p_accuracy is null or p_accuracy<=0 or p_accuracy>100 then raise exception 'Akurasi lokasi terlalu rendah.';end if;v_distance:=6371000*2*asin(sqrt(power(sin(radians(p_lat-(-5.382060))/2),2)+cos(radians(-5.382060))*cos(radians(p_lat))*power(sin(radians(p_lng-105.257840)/2),2)));if v_distance>180 then raise exception 'Absensi ditolak: Anda berada sekitar % meter dari titik kampus.',round(v_distance);end if;insert into public.attendance(student_id,tanggal,jam,status,recorded_by,latitude,longitude,accuracy_meters,distance_meters,location_valid) values(p_student_id,current_date,localtime,'Hadir',auth.uid(),p_lat,p_lng,p_accuracy,v_distance,true) on conflict(student_id,tanggal) do update set jam=excluded.jam,status='Hadir',recorded_by=auth.uid(),latitude=excluded.latitude,longitude=excluded.longitude,accuracy_meters=excluded.accuracy_meters,distance_meters=excluded.distance_meters,location_valid=true returning id into v_id;return json_build_object('success',true,'id',v_id,'distance_meters',round(v_distance),'accuracy_meters',round(p_accuracy));end;$$;
revoke all on function public.submit_attendance(uuid,double precision,double precision,double precision) from public,anon;grant execute on function public.submit_attendance(uuid,double precision,double precision,double precision) to authenticated;grant usage on schema public to authenticated;grant select on public.profiles to authenticated;
-- ADMIN: ganti EMAIL_ADMIN lalu jalankan:
-- insert into public.profiles(id,role) select id,'admin' from auth.users where email='EMAIL_ADMIN' on conflict(id) do update set role='admin';
-- MAHASISWA: setelah membuat user di Authentication > Users, ganti UUID_USER dan NPM:
-- insert into public.profiles(id,role,student_id) values('UUID_USER','mahasiswa',(select id from public.students where npm='24110002'));
